Try again loading forge
Loading async...
Package ‘magit’ installed.

Error: file-missing ("Cannot open load file" "No such file or directory" "forge")
  require(forge nil nil)
  #f(lambda () :dynbind (require 'forge nil nil))()
  eval-after-load(magit #f(lambda () :dynbind (require 'forge nil nil)))
  eval-buffer(#<buffer  *load*> nil "/Users/aar/src/drewr/dotemacs/d/init.el" nil t)
  load-with-code-conversion("/Users/aar/src/drewr/dotemacs/d/init.el" "/Users/aar/src/drewr/dotemacs/d/init.el" nil t)
  load("/Users/aar/src/drewr/dotemacs/d/init.el" nil t)
  command-line-1(("--eval" "(message \"----> running init\")" "-l" "d/setup.el" "-l" "d/init.el"))
  command-line()
  normal-top-level()
Cannot open load file: No such file or directory, forge
make: *** [load] Error 255